// 产物的隐式标识：写进文件元数据那几栏。
//
// 和水印那族同一个理由——错了不当场报错。写错栏名 mp4 的 muxer 直接把它
// 丢掉（连个警告都没有），摆错位置 ffmpeg 当成下一个输出的选项，漏一条
// 路径就是"某些片子没有标识"。全部按纯函数钉死。

#include <doctest/doctest.h>

#include <algorithm>
#include <string>
#include <vector>

#include "config/settings.hpp"
#include "media/assemble.hpp"
#include "media/product_tags.hpp"
#include "util/say.hpp"

using namespace changji;

namespace {

bool has(const std::string& hay, const std::string& needle) {
    return hay.find(needle) != std::string::npos;
}

/// 取出 `-metadata k=v` 里 k 那一栏的值。没有这一栏回空。
std::string tag(const std::vector<std::string>& args, const std::string& key) {
    for (std::size_t i = 0; i + 1 < args.size(); ++i) {
        if (args[i] != "-metadata") continue;
        const std::string& kv = args[i + 1];
        const auto eq = kv.find('=');
        if (eq != std::string::npos && kv.substr(0, eq) == key) {
            return kv.substr(eq + 1);
        }
    }
    return {};
}

std::vector<std::string> tag_keys(const std::vector<std::string>& args) {
    std::vector<std::string> keys;
    for (std::size_t i = 0; i + 1 < args.size(); ++i) {
        if (args[i] != "-metadata") continue;
        const auto eq = args[i + 1].find('=');
        if (eq != std::string::npos) keys.push_back(args[i + 1].substr(0, eq));
    }
    return keys;
}

}  // namespace

TEST_CASE("隐式标识：说清是 AI 生成的，带上工具") {
    const auto args = media::product_tag_args("2026-09-22T08:00:00+00:00");
    CHECK(has(tag(args, "comment"), "AI"));
    CHECK(has(tag(args, "description"), "人工智能生成合成"));
    // 中英各一份：给机器读的东西不能只有一种语言认得
    CHECK(has(tag(args, "description"), "generated by AI"));
    CHECK(has(tag(args, "comment"), "changji"));
    // 时间写在正文里，不写 creation_time——那一栏过一次重编码就没了（实测）
    CHECK(has(tag(args, "description"), "2026-09-22T08:00:00+00:00"));
    const auto keys = tag_keys(args);
    CHECK(std::find(keys.begin(), keys.end(), "creation_time") == keys.end());
}

TEST_CASE("隐式标识：只用容器认得的标准栏") {
    // mp4 的 muxer 把自定义 key 直接丢掉，实测 `-metadata cj_ai_generated=true`
    // 写完就没了，而且一声不响。加栏之前先确认那一栏 mp4 存得住。
    const auto keys = tag_keys(media::product_tag_args("t", "片名"));
    REQUIRE_FALSE(keys.empty());
    for (const auto& k : keys) {
        CAPTURE(k);
        CHECK((k == "title" || k == "comment" || k == "description"));
    }
}

TEST_CASE("隐式标识：片名知道才写") {
    const auto without = media::product_tag_args("t");
    CHECK(tag(without, "title").empty());

    const auto with = media::product_tag_args("t", "山那边");
    CHECK(tag(with, "title") == "山那边");
    // 多的只有片名这一栏，别的不跟着变
    CHECK(tag(with, "comment") == tag(without, "comment"));
    CHECK(tag(with, "description") == tag(without, "description"));
}

TEST_CASE("隐式标识：不跟着界面语言变") {
    // ⚠️ 这几句**不走 SAY**。元数据是给机器读的——跟着界面语言变的话，同一批
    // 产物在不同机器上写出不同的字，谁也解析不了。
    const std::string before = i18n::spoken();
    const auto zh = media::product_tag_args("t", "片名");
    i18n::speak("en");
    const auto en = media::product_tag_args("t", "片名");
    i18n::speak("ja");
    const auto ja = media::product_tag_args("t", "片名");
    i18n::speak(before);

    CHECK(zh == en);
    CHECK(zh == ja);
}

TEST_CASE("拼接：不给标识就和以前逐字节一样") {
    const auto plain = media::concat_args("list.txt", "out.mp4");
    const auto same = media::concat_args("list.txt", "out.mp4", {});
    CHECK(plain == same);
    CHECK(tag_keys(plain).empty());
}

TEST_CASE("拼接：标识摆在输出文件名之前") {
    // -metadata 是**输出选项**。摆到文件名后面，ffmpeg 会把它当成下一个输出
    // 的选项，而这条命令没有下一个输出——标识静悄悄丢掉。
    const auto args = media::concat_args("list.txt", "out.mp4",
                                         media::product_tag_args("t", "片名"));
    const auto out = std::find(args.begin(), args.end(), "out.mp4");
    const auto meta = std::find(args.begin(), args.end(), "-metadata");
    REQUIRE(out != args.end());
    REQUIRE(meta != args.end());
    CHECK(meta < out);
    // 输出文件名还是最后一个
    CHECK(out + 1 == args.end());
    // 零重编码那一条没被挤掉
    CHECK(std::find(args.begin(), args.end(), "copy") != args.end());
}
