#include "media/product_tags.hpp"

// CMake 给 changji_core 定义了它（PUBLIC）。留个兜底是因为测试那个 target
// 自己列源文件、不链 core，没有这一条就编不过——和 main.cpp 那份同一个理由。
#ifndef CHANGJI_VERSION
#define CHANGJI_VERSION "dev"
#endif

namespace changji::media {

namespace {

/// 这个二进制是谁。
std::string tool() { return std::string("场记 changji ") + CHANGJI_VERSION; }

}  // namespace

std::vector<std::string> product_tag_args(const std::string& stamp,
                                          const std::string& title) {
    std::vector<std::string> args;
    // 片名知道才写。不知道的时候与其填个 "ep01" 让播放器把它当片名显示，
    // 不如空着——这一栏是给人看的，另外两栏才是标识本身。
    if (!title.empty()) {
        args.push_back("-metadata");
        args.push_back("title=" + title);
    }
    args.push_back("-metadata");
    args.push_back("comment=AI 生成 / AI-generated · " + tool());
    args.push_back("-metadata");
    std::string desc = "本内容由人工智能生成合成 / This content was generated by AI · " + tool();
    if (!stamp.empty()) desc += " · " + stamp;
    args.push_back("description=" + desc);
    return args;
}

}  // namespace changji::media
